### ISSUE TITLE
Todo (20201227)

### ISSUE THREAD

**Issue by sweatpotato13** [sweatpotato13/some_project#16]
## 🚀 Proposal Detail

- [x] Multiple marker
- [x] 마커 클릭시 주소 정보 없을때 예외처리

**Comment by 201411108** [comment]
PR#_17_

**Comment by 201411108** [comment]
20210102
초롱 -> 무게중심 구하는 코드 작성
한동 -> multiple marker 구현

**Comment by 201411108** [comment]
closed 20200102
