### ISSUE TITLE
React Native version mismatch

### ISSUE THREAD

**Issue by 201411108** [sweatpotato13/some_project#5]
<img width="363" alt="Screen Shot 2020-10-22 at 2 35 14 AM" src="https://user-images.githubusercontent.com/37533787/96756937-b8a7c600-140f-11eb-9a74-f885b9f746eb.png">

@sweatpotato13 check your version and plz tell me

**Comment by sweatpotato13** [comment]
package.json 
`
  "dependencies": {
    "react-native": "0.61.2",
  }
`
