### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sweatpotato13** [sweatpotato13/some_project#8]
- [x] Naver API에서 좌표를 사용해서 세부정보 얻을 수 있는지 확인 -> Reverse Geocoding

- [x] 세부정보를 담을 수 있는 컴포넌트 작성

- [x] 주소검색창

**Comment by sweatpotato13** [comment]
Naver API에서 좌표를 사용해서 세부정보 얻을 수 있는지 확인
-> reverse geocoding 
네이버에서 api 지원함

**Comment by 201411108** [comment]
https://yannichoongs.tistory.com/163
-> 마커 띄우기 전에 화면에 해당 좌표에 세부 정보를 띄우고 ok 클릭 시 해당 좌표 고정

**Comment by 201411108** [comment]
@sweatpotato13 주소를 입력해서 장소 검색할 수 있는 검색 바도 구현해야 함! -> Geocoding도 사용해야 할 듯!

**Comment by sweatpotato13** [comment]
> @sweatpotato13 주소를 입력해서 장소 검색할 수 있는 검색 바도 구현해야 함! -> Geocoding도 사용해야 할 듯!

본문수정
